config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "bikes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  patch 'reservations/:id/accepted', to: 'reservations#accepted', as: 'accepted'
  patch 'reservations/:id/refused', to: 'reservations#refused', as: 'refused'
  get 'bikes/collection', to: 'bikes#collection', as: 'collection'


  resources :bikes, only: [:index, :new, :create, :show] do
    resources :reservations, only: :create, shallow: true
  end
  resources :reservations, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :reservations

  CATEGORIES = [
    "VTT",
    "VTC",
    "Tandem",
    "Rosalie",
    "Tricycle"
  ]

  validates :category, inclusion: { in: CATEGORIES }
  validates :description, presence: true
  validates :title, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :bike

end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bikes
  has_many :reservations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :password, :photo])
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_bike, only: [:show]

  def index

    @bikes = policy_scope(Bike)


    if params[:search].present?
      sql_query = " \
        bikes.title @@ :query \
        OR bikes.category @@ :query \
        OR bikes.address @@ :query \
      "
      @bikes = @bikes.where(sql_query, query: "%#{params[:search][:query]} #{params[:search][:category]}%")
    end

    if @bikes.empty?
      @bikes = Bike.near(params[:search][:query], 50)
    end

    @bikes = @bikes.where.not(latitude: nil, longitude: nil).order(created_at: :desc)
    image = ActionController::Base.helpers.asset_path("logo_velo_small.png")
    @markers = @bikes.map do |bike|
      {
       lat: bike.latitude,
       lng: bike.longitude,
       icon: image
      }
    end
  end

  def show
    @reservation = Reservation.new
    authorize @bike
  end

  def new
    @bike = Bike.new
    authorize @bike
  end

  def create
    @bike = Bike.new(set_params)
    @bike.user = current_user
    authorize @bike
    sleep 1
    if @bike.save
      redirect_to collection_path
    else
      render :new
    end
  end

  def collection
    @bike = Bike.new
    authorize @bike

    @user = current_user
    @user_bikes = @user.bikes.order(created_at: :desc)
  end

  private

  def set_params
    params.require(:bike).permit(:title, :category, :description, :photo, :address, :category)

  end

  # def set_params_search
  #   params.require(:search).permit(:address, :category)
  # end

  def set_bike
    @bike = Bike.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def create
    @reservation = Reservation.new(reservation_params)
    date_begin = params[:reservation][:date_begin]
    date_end = params[:reservation][:date_end]
    @reservation.date_begin = DateTime.strptime(date_begin, '%m/%d/%Y')
    @reservation.date_end = DateTime.strptime(date_end, '%m/%d/%Y')
    @bike = Bike.find(params[:bike_id])
    @reservation.bike = @bike
    @reservation.user = current_user
    authorize @bike
    authorize @reservation
    if @reservation.save
      redirect_to reservations_path
    else
      render "bikes/show"
    end
  end

  def index
    @reservations = policy_scope(Reservation.where(user_id: current_user))
  end

  def accepted
    @reservation = Reservation.find(params[:id])
    @reservation.status = true
    authorize @reservation
    @reservation.save
    redirect_to collection_path
  end

  def refused
    @reservation = Reservation.find(params[:id])
    @reservation.status = false
    authorize @reservation
    @reservation.save
    redirect_to collection_path
  end
  private

  def reservation_params
    params.require(:reservation).permit(:user, :bike, :status, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_photo(record)
    options = { class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" }
    if record.photo.present?
      cl_image_tag(record.photo, options)
    else
      image_tag('photo_uniq.png', options)
    end
  end


  def default_path_photo(record)
    if record.photo.present?
      cl_image_path record.photo
    else
      image_path('photo_uniq.png')
    end
  end

end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/collection.html.erb
<h3>My bikes</h3>

  <div class="container">
    <div class="row text-center">
     <%= link_to "Add a bike", new_bike_path, class: "btn btn-success green" %>
    </div>

    <div class="row">

      <% @user_bikes.each do |bike|%>
      <div class="col-md-8 col-md-offset-2">
        <div class="collection">
          <div class="collection-bike">

            <div class="collection-bike-photo ">
              <%= cl_image_tag default_path_photo(bike), height: 300, width: 380, crop: :fill %>

            </div>
            <div class="collection-bike-infos ">
              <h4><%= bike.title %></h4>
              <p><%= bike.description %></p>
              <p>Address: <%= bike.address %></p>
            </div>

          </div>

        <% if bike.reservations.empty? %>
          <p class="no-reservation">No reservations yet</p>
        <% else %>
          <div class="collection-reservations">
            <% bike.reservations.each do |reservation| %>
              <div class="collection-reservation">
                <div class="collection-reservation-user-picture">
                  <%= cl_image_tag reservation.user.photo, height: 50, width: 50, radius: "max", crop: :fill %>
                </div>

                <div class="collection-reservation-infos">
                  <% if reservation.status == nil %>
                    <p> <strong><%= reservation.user.first_name %> <%= reservation.user.last_name %></strong>
                    wants to ride your bike from <strong> <%= reservation.date_begin %></strong>
                    to <strong> <%= reservation.date_end %></strong> </p>
                  <% elsif reservation.status == "t" %>
                    <p> <strong><%= reservation.user.first_name %> <%= reservation.user.last_name %></strong>
                    will ride your bike from <strong> <%= reservation.date_begin %></strong>
                    to <strong> <%= reservation.date_end %></strong> </p>
                  <% else %>
                    <p> <strong><%= reservation.user.first_name %> <%= reservation.user.last_name %></strong>
                    will not ride your bike from <strong> <%= reservation.date_begin %></strong>
                    to <strong> <%= reservation.date_end %></strong> </p>
                  <%end %>
                </div>

                <div class="collection-reservation-acception">
                  <% if reservation.status == nil %>
                    <%= button_to "Accept", accepted_path(reservation), method: :patch, class: "btn btn-success" %>
                    <%= button_to "Refuse", refused_path(reservation), method: :patch, class: "btn btn-danger" %>
                  <% elsif reservation.status == "t" %>
                    <i class="fa fa-check-circle fa-3x" ></i>
                  <% else %>
                    <i class="fa fa-ban fa-3x"></i>
                  <% end %>
                </div>

              </div>
            <% end %>
          </div>

      <% end %>

      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/bikes/index.html.erb
<div class="wrapper">
  <div class="research form form-inline">
    <%= simple_form_for :search, url: bikes_path, method: :get do |f| %>
      <%= f.input :query, as: :string, input_html: { value: params[:query], id: "flat_address" }, label: false, class: "form-control", placeholder: "Type an address" %>
      <%= f.input :category, collection: Bike::CATEGORIES, label: false, class: "form-control", input_html: { placeholder: "Chose a category"} %>
      <%= f.button :submit, 'Ride!', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="main_container">


    <div id="map" class="hidden-xs hidden-sm" style="width: 100%; height: 100vh;" data-markers="<%= @markers.to_json %>"></div>

  <div class="cards-container container-fluid">



    <div class="row">
    <% @bikes.each do |bike| %>

      <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="card">

            <div class="card-photo" style="background-image: url('<%= default_path_photo(bike) %>');"></div>

          <div class="card-infos">
            <h6><strong><%= link_to bike.title, bike_path(bike) %></strong></h6>
            <P><%= bike.category %></p>
            <p class="card-address"><%= bike.address %></p>
          </div>

        </div>
      </div>

    <% end %>
    </div>

  </div>

</div>

app/views/bikes/new.html.erb
<div class="container">

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="block">
          <h1>Add a bike</h1>

            <%= simple_form_for @bike do |f| %>
              <%= f.input :title %>
              <%= f.input :category, collection: Bike::CATEGORIES %>
              <%= f.input :address, input_html: { id: "flat_address" } %>
              <%= f.input :description %>
              <%= f.input :photo %>
              <%= f.input :photo_cache, as: :hidden %>
              <%= f.button :submit, { class: "btn btn-success alert_sweet "} %>
            <% end %>

          <%= link_to "< Back to Bikes", bikes_path %>
        </div>
      </div>
    </div>
</div>

app/views/bikes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="bike">

        <div class="bike-infos">
          <h1><%= @bike.title %></h1>
          <!-- <div class="bike-photo"> -->
            <% if @bike.photo.present? %>
              <%= cl_image_tag @bike.photo, height: 350 %>
            <% else %>
              <%= image_tag("photo_uniq.png", height: 250, width: 400, crop: :fill) %>
            <% end %>
          <!-- </div> -->

          <div class="bike-description">
            <p> <strong>Category:</strong>  <%= @bike.category %></p>
            <p> <strong>Description:</strong> <%= @bike.description %></p>
          </div>
        </div>

        <div class="bike-reservation text-center">
          <%= simple_form_for ([@bike, @reservation]) do |f| %>
          <%= f.input :date_begin, as: :string, label: "Riding day?", input_html: { class: "datepicker", data: { modal: true, "large-mode": true}, "data-theme": "date-style" } %>
          <%= f.input :date_end, as: :string, label: "Riding end?", input_html: { class: "datepicker", data: { modal: true, "large-mode": true}, "data-theme": "date-style" } %>
          <%= f.button :submit, "Book!", { class: "btn btn-success"} %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ride My Bike</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&key=<%= ENV['GOOGLE_API_SERVER_KEY'] %>" ></script>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<div class="dropdown">
  <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown trigger
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dLabel">
    ...
  </ul>
</div>

app/views/reservations/index.html.erb
<div class="container">
    <div class="row">
        <h3>Your reservations</h3>
        <% @reservations.each do |reservation| %>
        <div class="col-md-8 col-md-offset-2">

          <div class="reservation">
            <div class="reservation-photo">
              <%= cl_image_tag reservation.bike.photo, height: 140, width: 170, crop: :fill %>
            </div>

            <div class="reservation-infos">
              <h4> <strong><%= reservation.bike.title %></strong> </h4>
              <p> <%= reservation.bike.description %> </p>
              <p> <strong>Owner:</strong> <%= reservation.bike.user.first_name %> <%= reservation.bike.user.last_name %></p>
              <p> <%= reservation.bike.user.phone_number %> </p>
              <p> <%= reservation.bike.user.email %> </p>
              <p> <strong>From</strong> <%=reservation.date_begin %> <strong>to</strong> <%= reservation.date_end %></p>
            </div>

            <div class="reservation-status">
              <% if reservation.status == nil %>
                <h4>Pending </h4>
              <% elsif reservation.status == "t" %>
                <i class="fa fa-check-circle fa-4x" ></i>
              <% else %>
                <i class="fa fa-ban fa-4x"></i>
              <%end %>
            </div>

          </div>
        </div>
      <% end %>
    </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_velo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Add a bike", new_bike_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My reservations", reservations_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My bikes", collection_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= avatar_photo(current_user)%>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu" style="z-index: 11;">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>